#!/usr/bin/env bash

echo "Re-requesting OAUTH2 authorization: $(date)"
echo ""

if ! dpkg-query -W -f='${Status}' "offlineimap" 2>/dev/null | grep -q "ok installed"; then
    echo "Email tools are not installed. You should run: make gmail"
    exit 1
fi

#if [[ $# -eq 0 ]]; then
#    echo "Usage: $0 <emailprovider>"
#    exit 1
#fi

pushd .
cd $HOME/dewlinux/

python3 scripts/oauth2_config.py $1

popd

