#!/bin/bash
set -euo pipefail

export DEBIAN_FRONTEND="noninteractive"
trap 'echo "ERROR in ${BASH_SOURCE[0]} at line ${LINENO}: $BASH_COMMAND"; exit 130' INT

if [[ $# -gt 0 && "$1" == "help" ]]; then
    echo ""
    echo "FULL UPDATE   : update_system"
    echo "BRIEF UPDATE  : update_system brief"
    echo ""
    exit 2
fi

echo ""
echo "UPDATING THE SYSTEM..."
echo ""

pushd .
cd ~/dewlinux/

echo ""
echo "Acquiring updates..."
sudo apt update
sudo apt -y upgrade

echo ""
echo "Updating PROJECT DEW codebase..."
git pull

# If first parameter is set to "brief", this will NOT be executed
# (as it takes lots of time)
if [[ $# -eq 0 || "$1" != "brief" ]]; then
    rm -rf /tmp/mdterm
    rm -rf /tmp/wiki-tui
    echo ""
    echo "Downloading additional updates..."
    git clone --depth 1 https://github.com/bahdotsh/mdterm.git /tmp/mdterm
    git clone --depth 1 https://github.com/Builditluc/wiki-tui /tmp/wiki-tui

    echo ""
    echo "Installing additional updates..."
    cargo install -q --path /tmp/wiki-tui/ --force
    cargo install -q --path /tmp/mdterm/ --force
    cargo install rgx-cli --force
    cargo install xleak --force
    cargo install chess-tui --force
fi

# Versioning check
if [[ ! -v DEWVERSION ]]; then
    printf "\nexport DEWVERSION=1\n\n" >> ~/.profile
    source ~/.profile

    sudo cp configs/motd /etc/motd

    # Creating symlinks
    ln -sf ~/dewlinux/scripts/listusb ~/bin/listusb
    ln -sf ~/dewlinux/scripts/removeusb ~/bin/removeusb
    ln -sf ~/dewlinux/scripts/myip ~/bin/myip
    ln -sf ~/dewlinux/pull_google_contacts ~/bin/pull_google_contacts
    ln -sf ~/dewlinux/play_chess ~/bin/play_chess
    ln -sf ~/dewlinux/dewhelp ~/bin/dewhelp
    ln -sf ~/dewlinux/update_system ~/bin/update_system
    ln -sf ~/dewlinux/sync_mail ~/bin/sync_mail
    ln -sf ~/dewlinux/reauthorize ~/bin/reauthorize
    ln -sf ~/dewlinux/scripts/battery ~/bin/battery

    cp scripts/get_mail_secret.py ~/bin
    chmod 700 ~/bin/get_mail_secret.py

    sudo apt -y install upower

    # Nice to have
    wget "https://www.markdownguide.org/assets/markdown-cheat-sheet.md" -O ~/dewlinux/markdown-cheat-sheet.md
    
    echo ""
    echo "THE SYSTEM WAS UPDATED TO VERSION 1. YOU BETTER LOGOFF AND LOGIN AGAIN."
fi

popd

echo ""
echo "SYSTEM UPDATED."
