#!/bin/bash
set -euo pipefail

export DEBIAN_FRONTEND="noninteractive"
trap 'echo "ERROR in ${BASH_SOURCE[0]} at line ${LINENO}: $BASH_COMMAND"; exit 130' INT

echo ""
echo "UPDATING THE SYSTEM..."
echo ""

pushd .
cd $HOME/dewlinux/

echo "Acquiring updates..."
sudo apt update
sudo apt -y upgrade

echo "Updating PROJECT DEW codebase..."
git pull

echo "Downloading additional updates..."
git -C wiki-tui/ pull
git -C mdterm/ pull
git -C lazytail/ pull

echo "Installing additional updates..."
cargo install --path wiki-tui/
cargo install --path mdterm/
cargo install rgx-cli
cargo install xleak
cargo install chess-tui

bash lazytail/install.sh
# lazytail init

# If the user is updating from a version before I made these changes
# then we need to do these

sudo cp configs/motd /etc/motd

# Creating symlinks
ln -sf $HOME/dewlinux/scripts/listusb ~/bin/listusb
ln -sf $HOME/dewlinux/scripts/removeusb ~/bin/removeusb
ln -sf $HOME/dewlinux/scripts/myip ~/bin/myip
ln -sf $HOME/dewlinux/pull_google_contacts ~/bin/pull_google_contacts
ln -sf $HOME/dewlinux/play_chess ~/bin/play_chess
ln -sf $HOME/dewlinux/dewhelp ~/bin/dewhelp
ln -sf $HOME/dewlinux/update_system ~/bin/update_system
ln -sf $HOME/dewlinux/sync_mail ~/bin/sync_mail
ln -sf $HOME/dewlinux/reauthorize ~/bin/reauthorize

popd

echo ""
echo "SYSTEM UPDATED."
