#!/bin/bash
set -euo pipefail

TOTALUPDATES=6

export DEBIAN_FRONTEND="noninteractive"
trap 'echo "ERROR in ${BASH_SOURCE[0]} at line ${LINENO}: $BASH_COMMAND"; exit 130' INT

if [[ $# -gt 0 && "$1" == "help" ]]; then
    echo ""
    echo "FULL UPDATE   : update_system"
    echo "BRIEF UPDATE  : update_system brief"
    echo ""
    exit 2
fi

echo ""
echo "UPDATING THE SYSTEM..."
echo ""

pushd . > /dev/null
cd ~/dewlinux/

echo "[1/${TOTALUPDATES}] Acquiring Debian updates..."
echo ""
sudo apt update
sudo apt -y upgrade

echo ""
echo "[2/${TOTALUPDATES}] Updating PROJECT DEW codebase..."
git pull

# If first parameter is set to "brief", this will NOT be executed
# (as it takes lots of time)
if [[ $# -eq 0 || "$1" != "brief" ]]; then
    echo ""
    echo "(The folowing updates would take more time, please be patient and do not interrupt this installation)"
    echo ""
    
    rm -rf /tmp/mdterm
    rm -rf /tmp/wiki-tui
    
    rm -rf /tmp/wiki-tui
    git clone -q --depth 1 https://github.com/Builditluc/wiki-tui /tmp/wiki-tui
    echo "[3/${TOTALUPDATES}] Compiling wiki-tui..."
    cargo install -q --path /tmp/wiki-tui/ --force
    rm -rf /tmp/wiki-tui
    
    echo "[4/${TOTALUPDATES}] Compiling mdterm..."
    rm -rf /tmp/mdterm
    git clone -q --depth 1 https://github.com/bahdotsh/mdterm.git /tmp/mdterm
    cargo install -q --path /tmp/mdterm/ --force
    rm -rf /tmp/mdterm
    
    echo "[5/${TOTALUPDATES}] Compiling rgx-cli..."
    cargo install -q rgx-cli --force
    
    echo "[6/${TOTALUPDATES}] Compiling xleak..."
    cargo install -q xleak --force
fi

# Versioning check
if [[ ! -v DEWVERSION ]]; then
    echo "*** Applying PROJECT DEW VERSION 1 updates..."
    
    if [ -f ~/.profile ] || ! grep -q "DEWVERSION" ~/.profile; then
        printf "\nexport DEWVERSION=1\n\n" >> ~/.profile
        source ~/.profile
    fi

    sudo cp -f configs/motd /etc/motd

    # Creating symlinks
    ln -sf ~/dewlinux/scripts/listusb ~/bin/listusb
    ln -sf ~/dewlinux/scripts/removeusb ~/bin/removeusb
    ln -sf ~/dewlinux/scripts/myip ~/bin/myip
    ln -sf ~/dewlinux/pull_google_contacts ~/bin/pull_google_contacts
    ln -sf ~/dewlinux/play_chess ~/bin/play_chess
    ln -sf ~/dewlinux/dewhelp ~/bin/dewhelp
    ln -sf ~/dewlinux/update_system ~/bin/update_system
    ln -sf ~/dewlinux/sync_mail ~/bin/sync_mail
    ln -sf ~/dewlinux/reauthorize ~/bin/reauthorize
    ln -sf ~/dewlinux/scripts/battery ~/bin/battery

    cp -f scripts/get_mail_secret.py ~/bin
    chmod 700 ~/bin/get_mail_secret.py

    sudo apt -y -qq --no-upgrade install upower

    # Nice to have
    [ -f ~/dewlinux/markdown-cheat-sheet.md ] || wget "https://www.markdownguide.org/assets/markdown-cheat-sheet.md" -O ~/dewlinux/markdown-cheat-sheet.md
    
    echo ""
    echo "THE SYSTEM WAS UPDATED TO VERSION 1. YOU BETTER LOGOFF AND LOGIN AGAIN."
fi

popd > /dev/null

echo ""
echo "SYSTEM UPDATED."
